# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wtyczk1_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qgis._gui import QgsMapLayerComboBox



class Ui_Wtyczk1DialogBase(object):
    def setupUi(self, Wtyczk1DialogBase):
        Wtyczk1DialogBase.setObjectName("Wtyczk1DialogBase")
        Wtyczk1DialogBase.resize(425, 482)
        self.button_box = QtWidgets.QDialogButtonBox(Wtyczk1DialogBase)
        self.button_box.setGeometry(QtCore.QRect(210, 420, 201, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.Pole = QtWidgets.QLabel(Wtyczk1DialogBase)
        self.Pole.setGeometry(QtCore.QRect(50, 30, 121, 31))
        self.Pole.setObjectName("Pole")
        self.pushButton_Pole = QtWidgets.QPushButton(Wtyczk1DialogBase)
        self.pushButton_Pole.setGeometry(QtCore.QRect(30, 110, 93, 28))
        self.pushButton_Pole.setObjectName("pushButton_Pole")
        self.pushButton_Roz_H = QtWidgets.QPushButton(Wtyczk1DialogBase)
        self.pushButton_Roz_H.setGeometry(QtCore.QRect(250, 110, 93, 28))
        self.pushButton_Roz_H.setObjectName("pushButton_Roz_H")
        self.label = QtWidgets.QLabel(Wtyczk1DialogBase)
        self.label.setGeometry(QtCore.QRect(260, 40, 71, 31))
        self.label.setObjectName("label")
        self.mMapLayerComboBox_warstwy = QgsMapLayerComboBox(Wtyczk1DialogBase)
        self.mMapLayerComboBox_warstwy.setGeometry(QtCore.QRect(30, 170, 160, 27))
        self.mMapLayerComboBox_warstwy.setObjectName("mMapLayerComboBox_warstwy")
        self.textBrowser_komunikaty = QtWidgets.QTextBrowser(Wtyczk1DialogBase)
        self.textBrowser_komunikaty.setGeometry(QtCore.QRect(30, 210, 256, 192))
        self.textBrowser_komunikaty.setObjectName("textBrowser_komunikaty")

        self.retranslateUi(Wtyczk1DialogBase)
        self.button_box.accepted.connect(Wtyczk1DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Wtyczk1DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Wtyczk1DialogBase)

    def retranslateUi(self, Wtyczk1DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Wtyczk1DialogBase.setWindowTitle(_translate("Wtyczk1DialogBase", "Wtyczk1"))
        self.Pole.setText(_translate("Wtyczk1DialogBase", "Pole"))
        self.pushButton_Pole.setText(_translate("Wtyczk1DialogBase", "Oblicz Pole"))
        self.pushButton_Roz_H.setText(_translate("Wtyczk1DialogBase", "Oblicz dH"))
        self.label.setText(_translate("Wtyczk1DialogBase", "Różnica H"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wtyczk1DialogBase = QtWidgets.QDialog()
    ui = Ui_Wtyczk1DialogBase()
    ui.setupUi(Wtyczk1DialogBase)
    Wtyczk1DialogBase.show()
    sys.exit(app.exec_())
